### ISSUE TITLE
Reservation timer concurrent modification error

### ISSUE THREAD

**Issue by AlextheGreat1509** [Meeting-App-ISAAC/MeetingRoom-Backend#26]
It appears the reload function of the exchange connection and the reservation timer try to edit at the same time:

`Exception in thread "Timer-0" java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1042)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:996)
	at CalendarResource.ExchangeCalendar.ModifyRoomReservations(ExchangeCalendar.java:93)
	at CalendarResource.ExchangeCalendar.getRooms(ExchangeCalendar.java:163)
	at CalendarResource.ExchangeCalendar.Reload(ExchangeCalendar.java:109)
	at Communication.ReservationProvider.Reload(ReservationProvider.java:32)
	at Communication.server.ReservationTimer.refreshReservations(ReservationTimer.java:51)
	at Communication.server.ReservationTimer.run(ReservationTimer.java:36)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)`

**Comment by carlo-theunissen** [comment]
Resolved in 170c443605aa1b29e9a5e1e344891f58141e5c25
